# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 16157451ad51c182c5358f59ac554bb4f367129bd20cc1c41d6d2ab3f5261d1ee49114e8fde31b3590824bf202b15b9b2151febc2d2354a13e5986d1d200e84e

test:
  secret_key_base: ff53a859ba9c7fca877c1490e84331da88e34c519e068ae4f8e24c4a886f9a5275181449d4c84c82c3fa45ea34b43fa6d202e700328ff29bac8aa5b6b9344f9c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
